# MAP BASE
"""

level_map_X: list[str] = [
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T                                                          T",
"T    I  G                                                  T",
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]

"""

level_map_1: list[str] = [
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                          F                               S",
    "S                                                          S",
    "S              SSSSSSSSSSiiiiSS                            S",
    "S            SSSSSSSSSSSSSSSSSS                            S",
    "S                                                          S",
    "S                                                          S",
    "S       E                 A            K                   S",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWWSSSSSSSSSSSSS          S",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S    I  G                              B                   S",
    "SSSSSSSSSSSSSSSSSSSSSSWWSSSSSWWSSSSSSSSSSSSSSSSSSSSSLLLSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]

level_map_2: list[str] = [
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS                                           BACKLW",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                            SSSSSSSSSSSSSSSSSSSSSSSS      S",
    "S                                     SSS                  S",
    "S                                     SSS                  S",
    "S                                     SSS              SSSSS",
    "S                                     SSS                  S",
    "S                                     SSS                  S",
    "S                                     SSS            SSSSSSS",
    "S                                     SSS                  S",
    "S                                     SSS                  S",
    "S                                     SSSSSSSSSS           S",
    "S                                     SSS                  S",
    "S                                     SSS                  S",
    "S                                     SSS            SSSSSSS",
    "S            F                        SSS                  S",
    "S                                     SSS                  S",
    "SSSSSSSSSSSSiiiiSSSSS                 SSSSSSSSSS           S",
    "S                                                          S",
    "S                                                          S",
    "S                                                    SSSSSSS",
    "S                                                          S",
    "S    I  G                                                  S",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]

level_map_3: list[str] = [
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS      BACKLW",
    "S                                                         S",
    "S                                                          S",
    "S                                                          S",
    "S              SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS    S",
    "S              S                                       S   S",
    "S          F   S                                           S",
    "S      K       S                                           S",
    "S   SSSSSiiiiSSS    SSS                                    S",
    "S              S    S S  SSSS         K                   SS",
    "S              S    S S          SSSSSSSSSSS               S",
    "S              S    S S                                    S",
    "S              S    S S                                    S",
    "S              S    S S                                    S",
    "S              S    S SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSS",
    "S              S    S                              S       S",
    "S              S    S                              S       S",
    "S              S    S                              SSS     S",
    "S              S    S                              S       S",
    "S                   S                              S       S",
    "S                   S                              S       S",
    "SLLLSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSS",
    "SSSSSSSSSSSSSSSS               S                S  S       S",
    "S              S               S                S  S       S",
    "S              S               S                S  S       S",
    "S              SSSSSSSSSSSSSSSSS    SSSSSSSS    SSSSSSS    S",
    "S                                   S      S               S",
    "S    I  G   K                       S      S               S",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]


level_choice: list[str] = [
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS        SWLBA",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                     B         I          S",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   SSSS",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S   ",
    "S                                                          S   ",
    "S                                                          S   ",
    "S                                                          S   ",
    "S                                                          S   ",
    "S                                                          S   ",
    "S                       G                                  S   ",
    "S                                      B                   S    ",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSLLLSSSS ",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]


level_map_4: list[str] = [
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S              SSSSSSSSSSS                                 S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                          F                               S",
    "S                                                          S",
    "S              SSSSSSSSSSiiiiSS                            S",
    "S            SSSSSSSSSSSSSSSSSS                            S",
    "S                                                          S",
    "S                                                          S",
    "S       E                 A            K                   S",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWWSSSSSSSSSSSSS          S",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS          S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S    I  G                              B                   S",
    "SSSSSSSSSSSSSSSSSSSSSSWWSSSSSWWSSSSSSSSSSSSSSSSSSSSSLLLSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]

level_map_5: list[str] = [
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS      BACKLW",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "S                      F                                   S",
    "S               K                                          S",
    "S       SSSSSSSSSSSSSSiiiiSSS                              S",
    "S                                                          S",
    "S                                                          S",
    "S                                                          S",
    "SPPP                                                       S",
    "S                                                          S",
    "S                                                          S",
    "S          PPPPP                                           S",
    "S                                                          S",
    "S                PPPPPPPPPPPPPPLLLPPPPPPPPPPPPPPPP         S",
    "SPPPP                                                      S",
    "S                                                          S",
    "S                 P                                        S",
    "S         PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPS",
    "S         T     T                                          S",
    "S                                                          S",
    "STTTTTT      T     T     T     T     T     T     T         S",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS    S",
    "S               S     S     S     S     S     S     S      S",
    "S               S     S     S     S     S     S     S      S",
    "S            S     S     S     S     S     S     S     SSSSS",
    "S   I   G    S     S     S     S     S     S     S     S   S",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]

level_map_6: list[str] = [
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS      BACKLW",
    "T                                                          T",
    "T                                                          T",
    "TT                                                         T",
    "T                                                      F   T",
    "T                                                          T",
    "T      TT    TT   TT   TT   TT  TT  TT  TTTTT TTT  SSSiiiiSS",
    "TTT                                                        T",
    "T                                                          T",
    "T                                                          T",
    "T                                                          T",
    "TTTTTT                                         H           T",
    "T         H          H                                     T",
    "T               H        H           A E   A       H       T",
    "T                            H    H   SSSSS                T",
    "T                                                          T",
    "T                                                        TTT",
    "T                                                          T",
    "T                                                          T",
    "T                                                       TTTT",
    "T                                    H        H         T  T",
    "T                              H                   H   HTTTT",
    "T                                         H                T",
    "T                       H                                  T",
    "T                                                          T",
    "T                                                          T",
    "T                                                          T",
    "T    I  G      PPPP                                        T",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]

level_map_7: list[str] = [
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "T                                                          S",
    "T                        F                                 S",
    "T                                                          S",
    "T              SSSSSSSSSiiiiSSSSSSS                        S",
    "T                                        SSS               S",
    "T                                    SS         SSS        S",
    "T                                                          S",
    "T                                                       SSSS",
    "T               SSSS                                       S",
    "T           SS      S                                      S",
    "T     SS             SA                   E            A   S",
    "T                     SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS    S",
    "T  K                                                       T",
    "TTTT                                                       T",
    "T                    TT                                    T",
    "T       HH    HH        TT                                 T",
    "T    HH         HH          TTT                            T",
    "T                                TTT                       T",
    "T                                      PPPPPPPPPPPPPPPPP   T",
    "T                                                  A       T",
    "T                                                  A       T",
    "T                                                  A       T",
    "T                                                  A       T",
    "T                                                  A       T",
    "T                                                  A       T",
    "T                                                          T",
    "T    I  G       B                                       LLLT",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]

level_map_8: list[str] = [
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS    B",
    "T                                                          T",
    "T                                                        F T",
    "T                                                          T",
    "T                                                    SSiiiiS",
    "T                                               TT         T",
    "T                  TT                       TT             T",
    "T                                                          T",
    "T              TT                                          T",
    "TT        TT             TT    TT        TT                T",
    "T                                    TT                    T",
    "T                                                          T",
    "T                                                          T",
    "TTTT                                                       T",
    "T                                                          T",
    "T                   TTT  TT  TT  TT  TT  TT                T",
    "T                                                          T",
    "TTTTTT                                        TT           T",
    "T                                                  TT     TT",
    "T                                                          T",
    "TTTTTTTTTTTTT                                              T",
    "T                                                          T",
    "T                                                        TTT",
    "T                                                          T",
    "T                                                          T",
    "T                                 HHH                      T",
    "T                         HHH                          TTTTT",
    "T    I  G        HHH                      SSS      H       T",
    "PPPPPPPPPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSWWWWWWWWWWWWWWP",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]

level_map_9: list[str] = [
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   B",
    "T                                                          T",
    "T                                                          T",
    "T                  SS                                      T",
    "T               SSS                                        T",
    "T                                                          T",
    "T                                                          T",
    "T    SSS   SSS                                             T",
    "T                                                          T",
    "T                                                          T",
    "TH                                                         T",
    "T                                                          T",
    "T                                                          T",
    "T                                                          T",
    "TH                                                         T",
    "T   H                                                F     T",
    "T           H                                              T",
    "T                         S   SSS  S  S  S    SSSSSiiiiSSSST",
    "T                                                          T",
    "T                                                          T",
    "T           H                                              T",
    "T                                                          T",
    "T                                                          T",
    "T                                                          T",
    "T           H                                              T",
    "T                                                          T",
    "T                                                          T",
    "T    I  G                                                  T",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]


# szélesség:60 karakter
# magasság: 30 sor

# A: barrier
# B: button
# C: Activate
# D: Asztal
# F: Főbejárat
# E: enemy
# G: Gépész
# I: Infós
# i: Finished_check
# K: Switch
# L: lift
# P: Parketta
# S: street
# s: Szék
# T: Csempe
# W: water
# H: platform
tile_size: int = 32
WIDTH, HEIGHT = 1900, len(level_map_1) * tile_size
